/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class inscriptionTest {
    @Test
    public static void main(String[] args) {
        boolean inscriptionReussie = inscription.inscriptions("khaoula@123","12345678");

        // Assert that inscription is successful
        assertTrue(inscriptionReussie);
    }


}