/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.util.Scanner;

public class inscription {

    // Rename the main method to inscription
    public static boolean inscriptions(String nomUtilisateur,String motDePasse ) {
        Scanner scanner = new Scanner(System.in);
        boolean inscriptionReussie = false;

        while (!inscriptionReussie) {
            System.out.print("Entrez votre nom d'utilisateur : ");
            nomUtilisateur = scanner.nextLine();

            System.out.print("Entrez votre mot de passe : ");
            motDePasse = scanner.nextLine();

            // Vérifications des conditions
            boolean conditionNomUtilisateur = !nomUtilisateur.matches("^[A-Z].*");
            boolean conditionNomUtilisateurAutres = !nomUtilisateur.matches(".*[a-z].*") || !nomUtilisateur.matches(".*\\d.*") || !nomUtilisateur.matches(".*[^a-zA-Z0-9].*");
            boolean conditionMotDePasse = motDePasse.length() != 8;

            if (conditionNomUtilisateur || conditionNomUtilisateurAutres || conditionMotDePasse) {
                System.out.println("Inscription échouée. Assurez-vous que le nom d'utilisateur commence par une lettre majuscule, et contient au moins une lettre minuscule, un chiffre et un symbole. Assurez-vous également que le mot de passe a une longueur de 8 caractères.\n");

                // Demander à l'utilisateur s'il veut réessayer
                System.out.print("Voulez-vous réessayer ? (oui/non) : ");
                String reponse = scanner.nextLine();

                if (!reponse.equalsIgnoreCase("oui")) {
                    break; // Sortir de la boucle si l'utilisateur ne veut pas réessayer
                }
            } else {
                inscriptionReussie = true;
                System.out.println("Inscription réussie pour l'utilisateur : " + nomUtilisateur);
            }
        }

        scanner.close();
        return inscriptionReussie;

    }
}
